### ISSUE TITLE
Help with MSI Summit E16 Flip (A12UCT model)

### ISSUE THREAD

**Issue by rottenpants466** [ThePBone/msi-ec-modern#1]
Hi, sorry to bother you. I have stumbled on your fork of [msi-ec](https://github.com/BeardOverflow/msi-ec) by BeardOverflow and i humbly ask you if you could help me figure out how to make some of the features work on my laptop by using this driver.

I've been trying to change the constants.h file to match the correct values of my laptop but with no success. I opened up a issue [here](https://github.com/BeardOverflow/msi-ec/issues/10) but i still have not got a response.

One of the things that interests me is the battery thresholds. I tried and installed your fork of msi-ec hoping that i could change the thresholds but nothing appears on system settings:

![Screenshot_20221124_235857](https://user-images.githubusercontent.com/62076029/203876118-e566dc01-4361-4a53-9fd5-0b4171fc52e4.png)

Thank you for your time

**Comment by timschneeb** [comment]
Hi, this kernel module doesn't add any settings to KDE's battery settings. It uses a custom sysfs setting.

You can try to write a new threshold value into EC using this command (if the kernel module is loaded):
For example, to set the medium charge threshold:
```bash
echo "medium" | sudo tee /sys/devices/platform/msi-ec/battery_charge_mode
```
To check the current setting (may need superuser too):
```bash
cat /sys/devices/platform/msi-ec/battery_charge_mode
```

Valid values (also in readme):
* **max**: best for mobility. Charge the battery to 100% all the time
* **medium**: balanced. Charge the battery when under 70%, stop at 80%
* **min**: best for battery. Charge the battery when under 50%, stop at 60%

Apparently, some models support setting two charging thresholds (original msi-ec supports this!); however, this isn't the case for my model, so I simplified the `battery_charge_mode` setting.

**Comment by rottenpants466** [comment]
Thank you for your response!

I just tested with `echo "medium" | sudo tee /sys/devices/platform/msi-ec/battery_charge_mode` and it works!

Does all of your fn keys work? i mean microphone mute, camera on/off, rotate screen?

Edit: also this is what i got:

```
[andre@SummitE16Flip ~]$ for f in /sys/devices/platform/msi-ec/*; do echo $f; cat $f; echo; done
/sys/devices/platform/msi-ec/ac_connected
1

/sys/devices/platform/msi-ec/battery_charge_mode
min

/sys/devices/platform/msi-ec/cooler_boost
off

/sys/devices/platform/msi-ec/cpu
cat: /sys/devices/platform/msi-ec/cpu: É pasta

/sys/devices/platform/msi-ec/driver
cat: /sys/devices/platform/msi-ec/driver: É pasta

/sys/devices/platform/msi-ec/driver_override
(null)

/sys/devices/platform/msi-ec/fan_mode
auto

/sys/devices/platform/msi-ec/fn_key
right

/sys/devices/platform/msi-ec/fw_release_date
2022/06/29 09:52:28

/sys/devices/platform/msi-ec/fw_version
1592EMS1.111

/sys/devices/platform/msi-ec/gpu
cat: /sys/devices/platform/msi-ec/gpu: É pasta

/sys/devices/platform/msi-ec/leds
cat: /sys/devices/platform/msi-ec/leds: É pasta

/sys/devices/platform/msi-ec/lid_open
1

/sys/devices/platform/msi-ec/modalias
platform:msi-ec

/sys/devices/platform/msi-ec/power
cat: /sys/devices/platform/msi-ec/power: É pasta

/sys/devices/platform/msi-ec/preset
custom

/sys/devices/platform/msi-ec/shift_mode
unknown (112)

/sys/devices/platform/msi-ec/subsystem
cat: /sys/devices/platform/msi-ec/subsystem: É pasta

/sys/devices/platform/msi-ec/uevent
DRIVER=msi-ec
MODALIAS=platform:msi-ec

/sys/devices/platform/msi-ec/webcam
on

/sys/devices/platform/msi-ec/win_key
left

[andre@SummitE16Flip ~]$ 
```

**Comment by timschneeb** [comment]
Yes, microphone mute, camera on/off all work using the kernel module.

For the rotate screen key, I set up a shell script that is bound to the rotate key using KDE's keyboard shortcut settings.

Shell script (only KDE supported): https://gist.github.com/ThePBone/caff2fef40358a79d6e4af7cf8f31074

Edit: forgot to add, you may need to change all the output numbers (currently 1) in the script. you can list all outputs using `kscreen-doctor -o`

**Comment by rottenpants466** [comment]
Thank you! 

For me the only key that doenst work is the mute microphone button. 

I think this driver should be included in the kernel out of the box! It would help other people using MSI laptops too.

One final question, i dont want to bother you, is your laptop convertible? I mean can you flip the screen? If so, does your keyboard and touchpad disable when you flip?

Thank you again!

**Comment by timschneeb** [comment]
No problem! No, my laptop isn't convertible. The screen can only be opened up to 180°.

**Comment by rottenpants466** [comment]
Sorry to bother you again, how can i adapt your code in order to make the battery thresholds appear in the system settings instead of having to type in the terminal every time i want to change the thresholds?

Thank you

**Comment by timschneeb** [comment]
You would need to add device properties for the charge controls like the original msi-ec has: https://github.com/BeardOverflow/msi-ec/blob/82adb09ea0d442670916ab7d3a13e51a9f6a3545/msi-ec.c#L133

I recommend you to use https://github.com/dmitry-s93/MControlCenter instead, though. It's a separate GUI app that can also set charging thresholds. I just noticed that the maintainer actually owns an MSI Summit E16 Flip themselves so it would be even more compatible with your device than my kernel module.

**Comment by rottenpants466** [comment]
Yeah i used that app when i was on Kubuntu, sadly now i cant used it because the ec_sys kernel module is not available in fedora and MControlCenter depends on it. Thats why i was hoping to use your code to enable certain features :(
